'use strict';
const $=id=>document.getElementById(id);
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categories={'在地小吃':'在地小吃','中式台菜':'台菜・中式','日韓料理':'日式・韓式','異國料理':'異國料理','火鍋燒烤居酒屋':'火鍋・燒烤','咖啡甜點冰品':'咖啡・甜點','景點步道':'景點・步道','住宿露營':'住宿・露營','購物伴手禮':'伴手禮'};
let places=[],category='',savedOnly=false,mapMode=false,selected=null,saved=new Set();
try{const stored=JSON.parse(localStorage.getItem('pocket-map-saved')||'[]');if(Array.isArray(stored))saved=new Set(stored.filter(Number.isInteger));}catch{}
function filtered(){const query=$('q').value.trim().toLowerCase().replaceAll('台','臺');return places.filter(p=>(!category||p.t===category)&&(!$('region').value||p.c===$('region').value)&&(!savedOnly||saved.has(p.id))&&(!query||[p.n,p.c,p.d,p.s,p.t].join(' ').toLowerCase().replaceAll('台','臺').includes(query))).sort((a,b)=>$('sort').value==='rating'?(b.r??-1)-(a.r??-1)||(b.k??-1)-(a.k??-1):$('sort').value==='reviews'?(b.k??-1)-(a.k??-1):a.id-b.id);}
function rating(p){return p.r==null?'資料不足，無法確認':`<span class="star">★ ${Number(p.r).toFixed(1)}</span> <small>${Number(p.k||0).toLocaleString()} 則評論 · 匯入評分</small>`;}
function safeURL(url){try{const u=new URL(url);return ['www.google.com','maps.google.com'].includes(u.hostname)&&['http:','https:'].includes(u.protocol)?u.href:'#';}catch{return '#';}}
function card(p){return `<article class="card ${selected===p.id?'selected':''}" data-id="${p.id}"><div class="card-top"><span class="type">${escapeHTML(categories[p.t])}</span><button class="save" data-action="save" aria-label="${saved.has(p.id)?'移除':'加入'}想去：${escapeHTML(p.n)}" aria-pressed="${saved.has(p.id)}">${saved.has(p.id)?'♥':'♡'}</button></div><h2><button class="title-button" data-action="detail">${escapeHTML(p.n)}</button></h2><p class="location">${escapeHTML(p.c)} · ${escapeHTML(p.d)}</p><p class="rating">${rating(p)}</p><p class="description">${escapeHTML(p.s)}</p><div class="tags">${p.l.map(x=>`<span>${escapeHTML(x)}</span>`).join('')}</div><div class="card-actions"><button data-action="map">在地圖查看</button><a href="${escapeHTML(safeURL(p.u))}" target="_blank" rel="noopener noreferrer">Google 地圖</a></div></article>`;}
function render(){const found=filtered();$('count').textContent=`${found.length} 個地點 / ${places.length} 個公開收藏`;$('savedCount').textContent=saved.size;$('results').innerHTML=found.length?found.map(card).join(''):'<div class="empty"><strong>這次沒有找到地點</strong><p>試試其他關鍵字，或重設篩選條件。</p></div>';if(mapMode){if(!found.some(p=>p.id===selected)&&found.length)selectMap(found[0]);$('mapPanel').hidden=!found.length;} }
function toggleSave(id){saved.has(id)?saved.delete(id):saved.add(id);try{localStorage.setItem('pocket-map-saved',JSON.stringify([...saved]));}catch{$('count').textContent='此瀏覽器無法儲存，想去清單僅保留至本次關閉網站。';}render();}
function selectMap(p){selected=p.id;$('mapTitle').textContent=p.n;const query=encodeURIComponent(`${p.c} ${p.d==='—'?'':p.d} ${p.n}`);const url=`https://www.google.com/maps?q=${query}&output=embed`;if($('map').getAttribute('src')!==url)$('map').src=url;$('mapLink').href=safeURL(p.u);}
function setView(isMap){mapMode=isMap;$('workspace').classList.toggle('map-mode',isMap);$('mapPanel').hidden=!isMap;$('mapView').setAttribute('aria-pressed',isMap);$('listView').setAttribute('aria-pressed',!isMap);render();}
function detail(p,random=false){$('detailBody').innerHTML=`<p class="eyebrow">${random?'今天的隨機下一站':escapeHTML(categories[p.t])}</p><h2>${escapeHTML(p.n)}</h2><p class="location">${escapeHTML(p.c)} · ${escapeHTML(p.d)}</p><p class="rating">${rating(p)}</p><p>${escapeHTML(p.s)}</p>${random?'<p class="location">從符合目前搜尋與篩選的收藏中隨機挑選。</p>':''}<button id="detailSave" aria-pressed="${saved.has(p.id)}">${saved.has(p.id)?'♥ 已加入想去':'♡ 加入想去'}</button> <a class="primary" href="${escapeHTML(safeURL(p.u))}" target="_blank" rel="noopener noreferrer">開啟 Google 地圖</a>`;$('detailSave').onclick=()=>{toggleSave(p.id);$('detailSave').textContent=saved.has(p.id)?'♥ 已加入想去':'♡ 加入想去';$('detailSave').setAttribute('aria-pressed',saved.has(p.id));};if(!$('detail').open)$('detail').showModal();}
$('q').addEventListener('input',render);$('region').addEventListener('change',render);$('sort').addEventListener('change',render);
$('saved').onclick=()=>{savedOnly=!savedOnly;$('saved').setAttribute('aria-pressed',savedOnly);render();};
$('categories').onclick=e=>{const b=e.target.closest('button');if(!b)return;category=b.dataset.category;for(const x of $('categories').querySelectorAll('button'))x.setAttribute('aria-pressed',x===b);render();};
$('reset').onclick=()=>{category='';savedOnly=false;$('q').value='';$('region').value='';$('sort').value='original';$('saved').setAttribute('aria-pressed','false');for(const b of $('categories').querySelectorAll('button'))b.setAttribute('aria-pressed',b.dataset.category==='');render();};
$('listView').onclick=()=>setView(false);$('mapView').onclick=()=>setView(true);
$('results').onclick=e=>{const b=e.target.closest('button[data-action]');if(!b)return;const p=places.find(x=>x.id===Number(b.closest('[data-id]').dataset.id));if(b.dataset.action==='save')toggleSave(p.id);else if(b.dataset.action==='detail')detail(p);else{selectMap(p);setView(true);$('mapPanel').scrollIntoView({block:'nearest',behavior:'instant'});}};
$('random').onclick=()=>{const found=filtered();if(found.length)detail(found[Math.floor(Math.random()*found.length)],true);else $('count').textContent='沒有符合條件的地點，請重設篩選後再挑選。';};
$('closeDetail').onclick=()=>$('detail').close();$('detail').addEventListener('click',e=>{if(e.target===$('detail')){const r=$('detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('detail').close();}});
fetch('places.json').then(r=>{if(!r.ok)throw new Error('載入失敗');return r.json();}).then(data=>{places=data;saved=new Set([...saved].filter(id=>places.some(p=>p.id===id)));const regions=[...new Set(places.map(p=>p.c))].sort((a,b)=>a==='臺南市'?-1:b==='臺南市'?1:a.localeCompare(b,'zh-Hant'));$('region').innerHTML+=[...regions].map(c=>`<option>${escapeHTML(c)}</option>`).join('');$('categories').innerHTML=`<button data-category="" aria-pressed="true">全部收藏</button>`+Object.entries(categories).map(([k,v])=>`<button data-category="${escapeHTML(k)}" aria-pressed="false">${v}</button>`).join('');render();}).catch(()=>{$('count').textContent='收藏資料暫時無法載入，請重新整理。';$('results').innerHTML='<div class="empty">無法取得收藏資料，請稍後再試。</div>';});
